// generated by OpenAI o4-mini
template<typename T>
T make_ndvector(const T &init) {
    return init;
}
template<typename T, typename... Dims>
auto make_ndvector(const T &init, std::size_t dim, Dims... dims) {
    using SubType = decltype(make_ndvector(init, dims...));
    return std::vector<SubType>(dim, make_ndvector(init, dims...));
}